import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import getConfig from "next/config";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const { publicRuntimeConfig } = getConfig();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // Use the canonical URL here
  metadataBase: new URL(publicRuntimeConfig.canonicalUrlCom || publicRuntimeConfig.canonicalUrlCa),
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="canonical"
          href={publicRuntimeConfig.canonicalUrlCom || publicRuntimeConfig.canonicalUrlCa}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
